DROP DATABASE IF EXISTS movies;

CREATE DATABASE IF NOT EXISTS movies;

USE movies;

CREATE TABLE IF NOT EXISTS movies(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
title VARCHAR(255) NOT NULL,
year SMALLINT NOT NULL,
PRIMARY KEY(id)
);